"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const AudioInstrument_1 = require("./AudioInstrument");
exports.AudioInstrument = AudioInstrument_1.AudioInstrument;
const AudioNote_1 = require("./AudioNote");
exports.AudioNote = AudioNote_1.AudioNote;
const Instrument_1 = require("./Instrument");
exports.Instrument = Instrument_1.Instrument;
const AbstractInstrumentManager_1 = require("./AbstractInstrumentManager");
exports.AbstractInstrumentManager = AbstractInstrumentManager_1.AbstractInstrumentManager;
const InstrumentManager_1 = require("./InstrumentManager");
exports.InstrumentManager = InstrumentManager_1.InstrumentManager;
const InstrumentManagerMock_1 = require("./InstrumentManagerMock");
exports.InstrumentManagerMock = InstrumentManagerMock_1.InstrumentManagerMock;
const MidiToMediaPlayer_1 = require("./MidiToMediaPlayer");
exports.MidiToMediaPlayer = MidiToMediaPlayer_1.MidiToMediaPlayer;
const SoundfontInstrument_1 = require("./SoundfontInstrument");
exports.SoundfontInstrument = SoundfontInstrument_1.SoundfontInstrument;
console.log("ww-music module loaded.");
//# sourceMappingURL=index.js.map